name: Build and deploy Next.js app to Azure Web App - dataviz-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Prisma generate + Next build)
        run: npm run build

      - name: Prepare deploy artifact
        run: |
          mkdir -p deploy
          cp -r .next deploy/
          cp -r public deploy/public
          cp -r prisma deploy/prisma
          cp package.json package-lock.json deploy/
          cp -r node_modules deploy/node_modules

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9C3E821FBDAE41CE8609EDBFA61D46BD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F9D446B39694FAD893C48B2C1728AB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_680C878C93E24FC497653962EAD18A0F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dataviz-app'
          slot-name: 'Production'
          package: .
